name: Android CI

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 17

      - name: Generate KeyStore
        run: |
          keytool -genkeypair -v -keystore my-release-key.jks -storepass ${{ secrets.KEYSTORE_PASSWORD }} -alias ${{ secrets.ALIAS }} -keypass ${{ secrets.KEY_PASSWORD }} -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=example.com, OU=ID, O=Organization, L=City, S=State, C=Country"

      - name: Encode KeyStore to Base64
        run: openssl base64 -A -in my-release-key.jks -out base64.txt

      - name: Make Gradle Executable
        run: chmod +x ./gradlew

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Sign AAB
        uses: r0adkll/sign-android-release@v1
        with:
          releaseDirectory: app/build/outputs/bundle/release
          signingKeyBase64: ${{ secrets.SIGNINGKEYBASE64 }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Build Release APK
        run: ./gradlew assembleRelease

      - name: Releasing APK
        uses: r0user/release-apk@main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}