name: Android CI
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
env:
  ANDROID_BUILD_TOOLS_VERSION: "34.0.0"
  ANDROID_COMPILE_SDK: 34
  ANDROID_TARGET_SDK: 34

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -e {0}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permissions for gradlew
        run: chmod +x ./gradlew

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
        with:
          sdk-version: "${{ env.ANDROID_BUILD_TOOLS_VERSION }}"

      - name: Print Gradle version
        run: ./gradlew -v

      - name: Build with Gradle
        run: ./gradlew bundleRelease  # Build the release bundle

      - name: Print Gradle Output Location
        run: |
          echo "Gradle output location: $(pwd)/app/build/outputs/bundle/release/"

      - name: Check APK File Existence
        run: |
          if [ ! -f "$(pwd)/app/build/outputs/bundle/release/app-release.aab" ]; then
            echo "Error: App Bundle file not found!"
            exit 1
          fi

      - name: Install Android Build Tools
        run: sdkmanager "build-tools;${ANDROID_BUILD_TOOLS_VERSION}"

      - name: Sign the App Bundle
        run: |
          # Decode the Android signing key and save it as keystore.jks
          echo "${{ secrets.ANDROID_SIGNING_KEY }}" | base64 -d > keystore.jks
          
          # Sign the App Bundle using apksigner from Android Build Tools
          "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS_VERSION}/apksigner" sign --ks keystore.jks --ks-pass pass:${{ secrets.KEYSTOREPASSWORD }} --ks-key-alias ${{ secrets.ALIAS }} --key-pass pass:${{ secrets.KEYPASSWORD }} --in app/build/outputs/bundle/release/app-release.aab --out app/build/outputs/bundle/release/app-release-signed.aab
          
          # Verify the signed App Bundle
          "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS_VERSION}/apksigner" verify --verbose app/build/outputs/bundle/release/app-release-signed.aab


      - name: Check Signed APK File Existence
        run: |
          if [ ! -f "$(pwd)/app-release-signed.apk" ]; then
            echo "Error: Signed APK file not found!"
            exit 1
          fi

      - name: Print Secret Variables for Debugging
        run: |
          echo "KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTOREPASSWORD }}"
          echo "KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYPASSWORD }}"

      - name: Upload App Bundle and Signed APK
        uses: actions/upload-artifact@v4
        with:
          name: android-artifacts
          path: |
            app/build/outputs/bundle/release/app-release.aab
            app-release-signed.apk
