name: Android Publish

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Update Gradle Wrapper
        run: ./gradlew wrapper --gradle-version=8.2

      - name: Download bundletool
        run: |
          mkdir -p $HOME/bin
          wget https://github.com/google/bundletool/releases/download/1.10.0/bundletool-all-1.10.0.jar -O $HOME/bin/bundletool.jar
          echo 'java -jar $HOME/bin/bundletool.jar "$@"' > $HOME/bin/bundletool
          chmod +x $HOME/bin/bundletool
          export PATH=$PATH:$HOME/bin

      - name: Run Tests
        run: ./gradlew test

      - name: Build Project
        run: ./gradlew build

      - name: Build Release AAB
        run: ./gradlew bundleRelease

      - name: Sign AAB
        run: |
          bundletool build-apks --bundle=app/build/outputs/bundle/release/app-release.aab --output=app/build/outputs/bundle/release/app-release-signed.apks
          apksigner sign --ks ${{ secrets.ANDROID_SIGNING_KEY }} --ks-pass pass:${{ secrets.KEYSTOREPASSWORD }} --ks-key-alias ${{ secrets.ALIAS }} --key-pass pass:${{ secrets.KEYPASSWORD }} --in app/build/outputs/bundle/release/app-release-signed.apks --out app/build/outputs/bundle/release/app-release-signed-aligned.apks

      - name: Sign APK
        run: |
          apksigner sign --ks ${{ secrets.ANDROID_SIGNING_KEY }} --ks-pass pass:${{ secrets.KEYSTOREPASSWORD }} --ks-key-alias ${{ secrets.ALIAS }} --key-pass pass:${{ secrets.KEYPASSWORD }} --in app/build/outputs/apk/release/app-release-unsigned.apk --out app/build/outputs/apk/release/app-release-signed.apk

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: release-artifacts
          path: |
            app/build/outputs/bundle/release/*.aab
            app/build/outputs/bundle/release/app-release-signed-aligned.apks
            app/build/outputs/apk/release/app-release-signed.apk

      - name: List Files
        run: |
          ls -R app/build/outputs/bundle/release/
          ls -R app/build/outputs/apk/release/

      - name: Display Artifact Token
        run: echo ${{ github.token }}
