name: Build and Sign APK and AAB

on:
  push:
    branches:
      - main

env:
  ANDROID_BUILD_TOOLS_VERSION: "34.0.0"
  ANDROID_COMPILE_SDK: 34
  PATH_UNSIGNED: "app/build/outputs"
  ANDROID_TARGET_SDK: 34
  CMD_TOOLS_VERSION: "10406996"

jobs:
  build_and_sign:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Install Android SDK
      run: |
        mkdir -p $ANDROID_HOME
        wget https://dl.google.com/android/repository/commandlinetools-linux-${CMD_TOOLS_VERSION}_latest.zip -O android_sdk.zip
        unzip -qq android_sdk.zip -d $ANDROID_HOME
        rm android_sdk.zip
        export PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin

    - name: Accept SDK licenses
      run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses
    
    - name: Update and Install SDK components
      run: |
        $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --update --sdk_root=$ANDROID_HOME
        yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager "platform-tools" "tools" "platforms;android-${ANDROID_COMPILE_SDK}" "build-tools;${ANDROID_BUILD_TOOLS_VERSION}" --sdk_root=$ANDROID_HOME
    
    - name: Build unsigned APK and AAB
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease bundleRelease

    - name: Decode Android Signing Key
      run: |
        echo "${{ secrets.ANDROID_SIGNING_KEY }}" | base64 -d > keystore.jks

    - name: Check Keystore File
      run: |
        if [ -s keystore.jks ]; then
          echo "Keystore file is not empty"
        else
          echo "Keystore file is empty"
          exit 1
        fi

    - name: Debug Keystore
      run: |
        ls -l keystore.jks
        tail keystore.jks
        wc -l keystore.jks

    - name: Verify Decoded Keystore
      run: keytool -list -v -keystore keystore.jks -storepass "${{ secrets.KEYSTOREPASSWORD }}"
      env:
        DECODED_SIGNING_KEY: ${{ env.DECODED_SIGNING_KEY }}
        
    - name: Sign APK
      run: |
        "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS_VERSION}/apksigner" sign --ks keystore.jks --ks-key-alias ${{ secrets.ALIAS }} --ks-pass pass:${{ secrets.KEYSTOREPASSWORD }} --in $(pwd)/${{ env.PATH_UNSIGNED }}/apk/release/app-release-unsigned.apk --out $(pwd)/${{ env.PATH_UNSIGNED }}/apk/release/app-release-signed.apk 

    - name: Verify Signed APK
      run: |
        "${ANDROID_HOME}/build-tools/${ANDROID_BUILD_TOOLS_VERSION}/apksigner" verify --verbose $(pwd)/${{ env.PATH_UNSIGNED }}/apk/release/app-release-signed.apk