name: Build and Release

on:
  push:
    branches:
      - 'main'

jobs:
  Build-and-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Debug: Show the commit message
      - name: Get the commit message
        run: |
          echo "Commit message: ${{ github.event.head_commit.message }}"

      - uses: kaisugi/action-regex-match@v1.0.0
        id: regex-match
        with:
          text: ${{ github.event.head_commit.message }}
          regex: 'version [0-9]+\.[0-9]+\.[0-9]+'

      # Debug: Show the result of the regex match commit
      - name: Debug regex match result
        run: | 
          echo "Regex Match Output: ${{ steps.regex-match.outputs.match }}"

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'gradle'

      - name: Build App
        run: |
          bash ./gradlew assembleRelease
          bash ./gradlew bundleRelease

      - name: Move files
        if: ${{ steps.regex-match.outputs.match != '' }}
        run: |
          mv app/build/outputs/apk/release/app-release-unsigned.apk app/build/outputs/app-release.apk
          mv app/build/outputs/bundle/release/app-release.aab app/build/outputs/app-release.aab

      - name: Sign App
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: upup-company/apksigner-android@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs
          signingKeyBase64: ${{ secrets.ANDROID_SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTOREPASSWORD }}
          keyPassword: ${{ secrets.KEYPASSWORD }}
        env:
          # override default build-tools version (29.0.3) -- optional
          BUILD_TOOLS_VERSION: "30.0.2"







      - name: Upload signedReleaseFile
      # Example use of `signedReleaseFile` output -- not needed
        uses: actions/upload-artifact@v2
        with:
          name: Signed app bundle
          path: ${{steps.sign_app.outputs.signedReleaseFile}}

      - name: Build Changelog
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: ardalanamini/auto-changelog@v3
        with:
          mention-authors: false
          mention-new-contributors: false
          include-compare: false
          semver: false

      - name: Create Release
        if: ${{ steps.regex-match.outputs.match != '' }}
        uses: ncipollo/release-action@v1.13.0
        with:
          artifacts: "app/build/outputs/app-release-signed.aab, app/build/outputs/app-release-signed.apk"
          body: ${{ steps.changelog.outputs.changelog }}
          tag: ${{ github.event.head_commit.message }}
          name: Release ${{ github.event.head_commit.message }}
          token: ${{ secrets.GITHUB_TOKEN }}